services:
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: sqlite:////data/meetup_helper.db
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/data

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  backend-data:

